# Generated by Django 4.2.4 on 2023-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_review_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
