# Generated by Django 4.2.4 on 2023-11-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_book_totalrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
    ]
